[package]
name = "seams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
chrono = "0.4.33"
gray_matter = "0.2.6"
html-escape = "0.2.13"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
serde_yaml = "0.9.30"
thiserror = "1.0.56"
toml = "0.8.8"
vfs = "0.10.0"
